"use client";

import { useState, useTransition, useEffect } from "react";
import { useRouter } from "next/navigation";
import { initializeRepo, previewPush, deliverToRepo, pollPrStatus } from "@/lib/actions/repo";
import { useToast } from "@/components/Toast";
import type { PushPreview } from "@/lib/actions/repo";
import type { RepoTreeEntry } from "@/lib/git/provider";

interface Props {
  projectId: string;
  projectName: string;
  configured: boolean;
  repoUrl: string | undefined;
  lastPushAt: string | null;
  lastPrUrl: string | null;
  prStatus: "open" | "merged" | "closed" | null;
  tree: RepoTreeEntry[] | null;
  gitProvider: string | null;
  gitRepoOwner: string | null;
  gitRepoName: string | null;
  hasGitToken: boolean;
}

const FILE_ICONS: Record<string, string> = {
  json: "{ }",
  yaml: "---",
  yml: "---",
  md: "#",
  tf: "HCL",
  groovy: "JF",
  makefile: "MK",
};

function getFileIcon(path: string): string {
  const ext = path.split(".").pop()?.toLowerCase() ?? "";
  return FILE_ICONS[ext] ?? "F";
}

function formatSize(bytes?: number): string {
  if (!bytes) return "";
  if (bytes < 1024) return `${bytes}B`;
  if (bytes < 1048576) return `${(bytes / 1024).toFixed(1)}KB`;
  return `${(bytes / 1048576).toFixed(1)}MB`;
}

export function RepoHub({
  projectId,
  projectName,
  configured,
  repoUrl,
  lastPushAt,
  lastPrUrl,
  prStatus,
  tree,
  gitProvider,
  gitRepoOwner,
  gitRepoName,
  hasGitToken,
}: Props) {
  const router = useRouter();
  const toast = useToast();
  const [initName, setInitName] = useState(projectName.toLowerCase().replace(/[^a-z0-9]+/g, "-"));
  const [initOrg, setInitOrg] = useState("postman-cs");
  const [creating, startCreate] = useTransition();
  const [pushing, startPush] = useTransition();
  const [msg, setMsg] = useState<{ ok: boolean; text: string } | null>(null);
  const [expandedDirs, setExpandedDirs] = useState<Set<string>>(new Set([""]));

  const [provider, setProvider] = useState<"github" | "gitlab" | "bitbucket">(
    (gitProvider as "github" | "gitlab" | "bitbucket") ?? "github"
  );
  type DeliveryStep = "idle" | "previewing" | "ready" | "initializing" | "pushing" | "done";
  const [deliveryStep, setDeliveryStep] = useState<DeliveryStep>("idle");
  const [preview, setPreview] = useState<PushPreview | null>(null);
  const [selectedCategories, setSelectedCategories] = useState({
    collections: true, pipelines: true, iac: true, tests: true, docs: true,
  });
  const [prTitle, setPrTitle] = useState(`CortexLab Delivery: ${projectName}`);
  const [prBody, setPrBody] = useState(
    `## CortexLab Engagement Delivery\n\nThis PR contains the engagement package generated by CortexLab for **${projectName}**.\n\n### Next Steps\n1. Review and merge this PR\n2. Configure CI/CD secrets\n3. Run the pipeline to validate`
  );
  const [polledPrStatus, setPolledPrStatus] = useState<"open" | "merged" | "closed" | null>(prStatus);

  const stepperSteps = configured
    ? ["Preview", "Configure", "Push", "Done"]
    : ["Preview", "Configure", "Init & Push", "Done"];

  const stepIndex = (() => {
    switch (deliveryStep) {
      case "idle": return -1;
      case "previewing": return 0;
      case "ready": return 1;
      case "initializing":
      case "pushing": return 2;
      case "done": return 3;
      default: return -1;
    }
  })();

  function handleInit() {
    setMsg(null);
    startCreate(async () => {
      const res = await initializeRepo(projectId, initName, initOrg, provider);
      if (res.error) {
        setMsg({ ok: false, text: res.error });
        toast.error("Repo creation failed", res.error);
      } else {
        setMsg({ ok: true, text: `Repo created: ${res.repo?.fullName}` });
        toast.success("Repository created", res.repo?.fullName);
        router.refresh();
      }
    });
  }

  function handlePreview() {
    setMsg(null);
    setDeliveryStep("previewing");
    startPush(async () => {
      const res = await previewPush(projectId);
      if (res.error) {
        setMsg({ ok: false, text: res.error });
        setDeliveryStep("idle");
      } else if (res.preview) {
        setPreview(res.preview);
        setDeliveryStep("ready");
      }
    });
  }

  function handleDeliver(includeInit: boolean) {
    setMsg(null);
    setDeliveryStep(includeInit ? "initializing" : "pushing");
    startPush(async () => {
      const res = await deliverToRepo(projectId, {
        initRepo: includeInit ? { repoName: initName, org: initOrg, provider } : undefined,
        selectedCategories,
        prTitle,
        prBody,
      });
      if (res.error) {
        setMsg({ ok: false, text: `${res.failedStep ? `[${res.failedStep}] ` : ""}${res.error}` });
        toast.error("Delivery failed", res.error);
        setDeliveryStep("ready");
      } else {
        setMsg({ ok: true, text: `PR created: ${res.pr?.url}` });
        toast.success("PR created successfully");
        setDeliveryStep("done");
        router.refresh();
      }
    });
  }

  useEffect(() => {
    if (!configured) return;
    const shouldPoll = polledPrStatus === "open" || deliveryStep === "done";
    if (!shouldPoll) return;
    let cancelled = false;
    const interval = setInterval(async () => {
      if (cancelled) return;
      const res = await pollPrStatus(projectId);
      if (!cancelled && res.status) {
        setPolledPrStatus(res.status);
        if (res.status === "merged" || res.status === "closed") clearInterval(interval);
      }
    }, 15000);
    return () => { cancelled = true; clearInterval(interval); };
  }, [configured, polledPrStatus, deliveryStep, projectId]);

  function toggleCategory(key: keyof typeof selectedCategories) {
    setSelectedCategories(prev => ({ ...prev, [key]: !prev[key] }));
  }

  function toggleDir(dir: string) {
    setExpandedDirs((prev) => {
      const next = new Set(prev);
      if (next.has(dir)) next.delete(dir);
      else next.add(dir);
      return next;
    });
  }

  const prStatusColors = {
    open: { bg: "rgba(59,130,246,0.1)", color: "#60a5fa", label: "Open" },
    merged: { bg: "rgba(16,185,129,0.1)", color: "#34d399", label: "Merged" },
    closed: { bg: "rgba(239,68,68,0.1)", color: "#f87171", label: "Closed" },
  };

  // Build tree structure
  type TreeNode = { name: string; path: string; type: "blob" | "tree"; size?: number; children: TreeNode[] };
  function buildTreeStructure(entries: RepoTreeEntry[] | null): TreeNode[] {
    if (!entries) return [];
    const root: TreeNode[] = [];
    const dirMap = new Map<string, TreeNode>();

    const sorted = [...entries].sort((a, b) => {
      if (a.type !== b.type) return a.type === "tree" ? -1 : 1;
      return a.path.localeCompare(b.path);
    });

    for (const entry of sorted) {
      const parts = entry.path.split("/");
      const node: TreeNode = { name: parts[parts.length - 1], path: entry.path, type: entry.type, size: entry.size, children: [] };
      if (entry.type === "tree") dirMap.set(entry.path, node);

      if (parts.length === 1) {
        root.push(node);
      } else {
        const parentPath = parts.slice(0, -1).join("/");
        const parent = dirMap.get(parentPath);
        if (parent) parent.children.push(node);
        else root.push(node);
      }
    }
    return root;
  }

  function renderTree(nodes: TreeNode[], depth: number = 0): React.ReactNode {
    return nodes.map((node) => {
      const isDir = node.type === "tree";
      const isExpanded = expandedDirs.has(node.path);
      return (
        <div key={node.path}>
          <div
            className={`flex items-center gap-2 py-1 px-2 rounded text-xs ${isDir ? "cursor-pointer hover:opacity-80" : ""}`}
            style={{ paddingLeft: `${depth * 16 + 8}px`, color: "var(--foreground)" }}
            onClick={isDir ? () => toggleDir(node.path) : undefined}
          >
            {isDir ? (
              <span className="w-4 text-center" style={{ color: "var(--accent-cyan)" }}>
                {isExpanded ? "▼" : "▶"}
              </span>
            ) : (
              <span className="w-4 text-center text-[9px] font-mono" style={{ color: "var(--foreground-dim)" }}>
                {getFileIcon(node.name)}
              </span>
            )}
            <span className={isDir ? "font-medium" : ""}>{node.name}</span>
            {node.size ? (
              <span className="ml-auto text-[10px]" style={{ color: "var(--foreground-dim)" }}>{formatSize(node.size)}</span>
            ) : null}
          </div>
          {isDir && isExpanded && node.children.length > 0 && renderTree(node.children, depth + 1)}
        </div>
      );
    });
  }

  const treeNodes = buildTreeStructure(tree);

  if (!configured && !hasGitToken) {
    return (
      <div className="card">
        <div className="text-center py-12">
          <div className="w-14 h-14 rounded-2xl mx-auto mb-4 flex items-center justify-center" style={{ background: "rgba(6,214,214,0.08)", border: "1px solid rgba(6,214,214,0.15)" }}>
            <svg className="w-7 h-7" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5} style={{ color: "var(--accent-cyan)" }}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M17.25 6.75L22.5 12l-5.25 5.25m-10.5 0L1.5 12l5.25-5.25m7.5-3l-4.5 16.5" />
            </svg>
          </div>
          <h3 className="text-lg font-semibold mb-2" style={{ color: "var(--foreground)" }}>Git Token Required</h3>
          <p className="text-sm max-w-md mx-auto" style={{ color: "var(--foreground-dim)" }}>
            To create and push to repos, add a GitHub Personal Access Token (PAT) in your project details under Integrations.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {msg && (
        <div className="rounded-lg px-4 py-3 text-sm" style={{
          background: msg.ok ? "rgba(16,185,129,0.06)" : "rgba(239,68,68,0.06)",
          border: `1px solid ${msg.ok ? "rgba(16,185,129,0.15)" : "rgba(239,68,68,0.15)"}`,
          color: msg.ok ? "#34d399" : "#f87171",
        }}>
          {msg.text}
        </div>
      )}

      {/* Delivery Progress Stepper */}
      {deliveryStep !== "idle" && (
        <div className="card">
          <div className="flex items-center gap-2">
            {stepperSteps.map((label, i) => {
              const active = i === stepIndex;
              const complete = stepIndex > i;
              return (
                <div key={label} className="flex items-center" style={{ flex: i < stepperSteps.length - 1 ? 1 : undefined }}>
                  <div className="flex items-center gap-1.5 shrink-0">
                    <div
                      className="w-5 h-5 rounded-full flex items-center justify-center text-[9px] font-bold"
                      style={{
                        background: complete ? "rgba(6,214,214,0.12)" : active ? "rgba(6,214,214,0.08)" : "transparent",
                        color: complete ? "var(--accent-cyan)" : active ? "var(--accent-cyan)" : "var(--foreground-dim)",
                        border: `1px solid ${complete ? "rgba(6,214,214,0.25)" : active ? "rgba(6,214,214,0.2)" : "var(--border)"}`,
                      }}
                    >
                      {complete ? "✓" : i + 1}
                    </div>
                    <span className="text-[11px]" style={{ color: complete ? "var(--foreground)" : active ? "var(--accent-cyan)" : "var(--foreground-dim)" }}>
                      {label}
                    </span>
                  </div>
                  {i < stepperSteps.length - 1 && (
                    <div className="flex-1 h-px mx-2" style={{ background: complete ? "rgba(6,214,214,0.25)" : "var(--border)" }} />
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Init Repo Section */}
      {!configured && (
        <div className="card">
          <h2 className="text-lg font-semibold mb-4" style={{ color: "var(--foreground)" }}>Initialize Repository</h2>
          <p className="text-sm mb-4" style={{ color: "var(--foreground-dim)" }}>
            Configure a repo under your org. GitHub repos are auto-created; GitLab/Bitbucket require an existing repo.
          </p>
          <div className="space-y-3">
            <div>
              <label className="text-[10px] font-medium uppercase tracking-wider block mb-1.5" style={{ color: "var(--foreground-dim)" }}>Provider</label>
              <div className="flex gap-2">
                {(["github", "gitlab", "bitbucket"] as const).map((p) => (
                  <button
                    key={p}
                    onClick={() => setProvider(p)}
                    className="px-3 py-1.5 rounded-md text-xs font-medium transition-colors"
                    style={{
                      background: provider === p ? "rgba(6,214,214,0.1)" : "transparent",
                      color: provider === p ? "var(--accent-cyan)" : "var(--foreground-dim)",
                      border: `1px solid ${provider === p ? "rgba(6,214,214,0.25)" : "var(--border)"}`,
                    }}
                  >
                    {p === "github" ? "GitHub" : p === "gitlab" ? "GitLab" : "Bitbucket"}
                  </button>
                ))}
              </div>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div>
                <label className="text-[10px] font-medium uppercase tracking-wider block mb-1" style={{ color: "var(--foreground-dim)" }}>Organization</label>
                <input value={initOrg} onChange={(e) => setInitOrg(e.target.value)} className="w-full rounded-md px-2.5 py-1.5 text-sm border outline-none" style={{ background: "var(--background-secondary)", borderColor: "var(--border)", color: "var(--foreground)" }} />
              </div>
              <div>
                <label className="text-[10px] font-medium uppercase tracking-wider block mb-1" style={{ color: "var(--foreground-dim)" }}>Repo Name</label>
                <input value={initName} onChange={(e) => setInitName(e.target.value)} className="w-full rounded-md px-2.5 py-1.5 text-sm border outline-none" style={{ background: "var(--background-secondary)", borderColor: "var(--border)", color: "var(--foreground)" }} />
              </div>
              <div className="flex items-end">
                <button onClick={handleInit} disabled={creating || !initName.trim()} className="w-full rounded-md px-4 py-1.5 text-sm font-medium transition-colors" style={{ background: "rgba(16,185,129,0.12)", color: "#34d399", border: "1px solid rgba(16,185,129,0.2)", opacity: creating ? 0.6 : 1 }}>
                  {creating ? "Creating…" : "Create Repo Only"}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Connected Repo Status */}
      {configured && (
        <div className="card">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold" style={{ color: "var(--foreground)" }}>Repository</h2>
            {repoUrl && (
              <a href={repoUrl} target="_blank" rel="noopener noreferrer" className="text-xs font-medium px-3 py-1 rounded-md" style={{ background: "rgba(6,214,214,0.06)", color: "var(--accent-cyan)", border: "1px solid rgba(6,214,214,0.12)" }}>
                Open on {gitProvider === "gitlab" ? "GitLab" : gitProvider === "bitbucket" ? "Bitbucket" : "GitHub"} ↗
              </a>
            )}
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-4">
            <div>
              <p className="text-[10px] uppercase tracking-wider" style={{ color: "var(--foreground-dim)" }}>Provider</p>
              <p className="text-sm font-medium" style={{ color: "var(--foreground)" }}>{gitProvider ?? "—"}</p>
            </div>
            <div>
              <p className="text-[10px] uppercase tracking-wider" style={{ color: "var(--foreground-dim)" }}>Repo</p>
              <p className="text-sm font-medium" style={{ color: "var(--foreground)" }}>{gitRepoOwner}/{gitRepoName}</p>
            </div>
            <div>
              <p className="text-[10px] uppercase tracking-wider" style={{ color: "var(--foreground-dim)" }}>Last Push</p>
              <p className="text-sm font-medium" style={{ color: "var(--foreground)" }}>
                {lastPushAt ? new Date(lastPushAt).toLocaleDateString() : "Never"}
              </p>
            </div>
            <div>
              <p className="text-[10px] uppercase tracking-wider" style={{ color: "var(--foreground-dim)" }}>PR Status</p>
              {polledPrStatus ? (
                <span className="inline-block text-xs font-medium px-2 py-0.5 rounded mt-0.5" style={{ background: prStatusColors[polledPrStatus].bg, color: prStatusColors[polledPrStatus].color }}>
                  {prStatusColors[polledPrStatus].label}
                </span>
              ) : (
                <p className="text-sm" style={{ color: "var(--foreground-dim)" }}>—</p>
              )}
            </div>
          </div>

          {lastPrUrl && (
            <a href={lastPrUrl} target="_blank" rel="noopener noreferrer" className="text-xs" style={{ color: "var(--accent-cyan)" }}>
              View latest PR ↗
            </a>
          )}
        </div>
      )}

      {/* Deliver Artifacts */}
      <div className="card">
        <h2 className="text-lg font-semibold mb-1" style={{ color: "var(--foreground)" }}>
          {configured ? "Deliver Artifacts" : "Deliver to Repo"}
        </h2>
        <p className="text-sm mb-4" style={{ color: "var(--foreground-dim)" }}>
          {configured
            ? "Build the engagement package, review artifacts, then push to the repo as a PR."
            : "Preview artifacts, then initialize a repo and push everything in one step."}
        </p>

        {deliveryStep === "idle" && (
          <button
            onClick={handlePreview}
            disabled={pushing || (!configured && !initName.trim())}
            className="rounded-md px-5 py-2 text-sm font-medium transition-colors"
            style={{
              background: "rgba(6,214,214,0.1)",
              color: "var(--accent-cyan)",
              border: "1px solid rgba(6,214,214,0.2)",
              opacity: pushing ? 0.6 : 1,
            }}
          >
            {pushing ? "Loading…" : "Preview Artifacts"}
          </button>
        )}

        {deliveryStep === "previewing" && (
          <div className="flex items-center gap-2 text-sm" style={{ color: "var(--foreground-dim)" }}>
            <div className="w-4 h-4 border-2 border-t-transparent rounded-full animate-spin" style={{ borderColor: "var(--accent-cyan)", borderTopColor: "transparent" }} />
            Building package preview…
          </div>
        )}

        {deliveryStep === "ready" && preview && (
          <div className="space-y-4">
            <div className="rounded-lg p-4" style={{ background: "var(--background)", border: "1px solid var(--border)" }}>
              <p className="text-xs font-medium uppercase tracking-wider mb-2" style={{ color: "var(--foreground-dim)" }}>Push Preview</p>
              <div className="flex flex-wrap gap-3 text-sm mb-4">
                {[
                  { label: "Collections", count: preview.summary.collections },
                  { label: "Pipelines", count: preview.summary.pipelines },
                  { label: "IaC files", count: preview.summary.iacSnippets },
                  { label: "Test scripts", count: preview.summary.testScripts },
                  { label: "Docs", count: preview.summary.docs },
                ].map(({ label, count }) => (
                  <span key={label} className="px-2 py-0.5 rounded text-xs" style={{ background: "rgba(6,214,214,0.06)", color: "var(--accent-cyan)", border: "1px solid rgba(6,214,214,0.1)" }}>
                    {count} {label}
                  </span>
                ))}
                <span className="px-2 py-0.5 rounded text-xs font-medium" style={{ background: "rgba(16,185,129,0.06)", color: "#34d399" }}>
                  {preview.summary.totalFiles} total
                </span>
              </div>

              <p className="text-xs font-medium uppercase tracking-wider mb-2" style={{ color: "var(--foreground-dim)" }}>Select Categories</p>
              <div className="space-y-1.5">
                {([
                  { key: "collections" as const, label: "Collections", files: preview.categories.collections },
                  { key: "pipelines" as const, label: "CI/CD Pipelines", files: preview.categories.pipelines },
                  { key: "iac" as const, label: "Infrastructure (IaC)", files: preview.categories.iac },
                  { key: "tests" as const, label: "Test Scripts", files: preview.categories.tests },
                  { key: "docs" as const, label: "Documentation", files: preview.categories.docs },
                ]).map(({ key, label, files }) => (
                  <label key={key} className="flex items-center gap-2 text-sm cursor-pointer py-0.5">
                    <input
                      type="checkbox"
                      checked={selectedCategories[key]}
                      onChange={() => toggleCategory(key)}
                      className="rounded"
                      style={{ accentColor: "var(--accent-cyan)" }}
                    />
                    <span style={{ color: selectedCategories[key] ? "var(--foreground)" : "var(--foreground-dim)" }}>{label}</span>
                    <span className="text-[10px]" style={{ color: "var(--foreground-dim)" }}>({files.length} files)</span>
                  </label>
                ))}
              </div>
            </div>

            <div className="space-y-3">
              <div>
                <label className="text-[10px] font-medium uppercase tracking-wider block mb-1" style={{ color: "var(--foreground-dim)" }}>PR Title</label>
                <input
                  value={prTitle}
                  onChange={(e) => setPrTitle(e.target.value)}
                  className="w-full rounded-md px-2.5 py-1.5 text-sm border outline-none"
                  style={{ background: "var(--background-secondary)", borderColor: "var(--border)", color: "var(--foreground)" }}
                />
              </div>
              <div>
                <label className="text-[10px] font-medium uppercase tracking-wider block mb-1" style={{ color: "var(--foreground-dim)" }}>PR Body</label>
                <textarea
                  value={prBody}
                  onChange={(e) => setPrBody(e.target.value)}
                  rows={5}
                  className="w-full rounded-md px-2.5 py-1.5 text-sm border outline-none resize-y"
                  style={{ background: "var(--background-secondary)", borderColor: "var(--border)", color: "var(--foreground)" }}
                />
              </div>
            </div>

            <div className="flex items-center gap-3">
              <button
                onClick={() => handleDeliver(!configured)}
                disabled={pushing || !Object.values(selectedCategories).some(Boolean)}
                className="rounded-md px-5 py-2 text-sm font-medium transition-colors"
                style={{
                  background: "rgba(16,185,129,0.12)",
                  color: "#34d399",
                  border: "1px solid rgba(16,185,129,0.2)",
                  opacity: pushing || !Object.values(selectedCategories).some(Boolean) ? 0.6 : 1,
                }}
              >
                {configured ? "Push to Repo" : "Initialize & Push"}
              </button>
              <button
                onClick={() => { setDeliveryStep("idle"); setPreview(null); }}
                className="rounded-md px-4 py-2 text-sm transition-colors"
                style={{ color: "var(--foreground-dim)", border: "1px solid var(--border)" }}
              >
                Cancel
              </button>
            </div>
          </div>
        )}

        {(deliveryStep === "initializing" || deliveryStep === "pushing") && (
          <div className="flex items-center gap-2 text-sm" style={{ color: "var(--foreground-dim)" }}>
            <div className="w-4 h-4 border-2 border-t-transparent rounded-full animate-spin" style={{ borderColor: "#34d399", borderTopColor: "transparent" }} />
            {deliveryStep === "initializing" ? "Creating repository…" : "Pushing artifacts & creating PR…"}
          </div>
        )}

        {deliveryStep === "done" && (
          <div className="space-y-3">
            <div className="flex items-center gap-2 text-sm" style={{ color: "#34d399" }}>
              <span className="w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-bold" style={{ background: "rgba(16,185,129,0.12)", border: "1px solid rgba(16,185,129,0.25)" }}>✓</span>
              Delivery complete — PR created successfully.
            </div>
            {polledPrStatus && (
              <div className="flex items-center gap-2 text-xs" style={{ color: "var(--foreground-dim)" }}>
                PR Status:
                <span className="px-2 py-0.5 rounded font-medium" style={{ background: prStatusColors[polledPrStatus].bg, color: prStatusColors[polledPrStatus].color }}>
                  {prStatusColors[polledPrStatus].label}
                </span>
                <span style={{ color: "var(--foreground-dim)" }}>(auto-refreshing)</span>
              </div>
            )}
            <button
              onClick={() => { setDeliveryStep("idle"); setPreview(null); }}
              className="rounded-md px-4 py-1.5 text-xs transition-colors"
              style={{ color: "var(--foreground-dim)", border: "1px solid var(--border)" }}
            >
              Start New Delivery
            </button>
          </div>
        )}
      </div>

      {/* File Tree */}
      {configured && tree && tree.length > 0 && (
        <div className="card">
          <h2 className="text-lg font-semibold mb-3" style={{ color: "var(--foreground)" }}>
            File Tree
            <span className="text-xs font-normal ml-2" style={{ color: "var(--foreground-dim)" }}>
              {tree.filter((e) => e.type === "blob").length} files
            </span>
          </h2>
          <div className="rounded-lg overflow-hidden" style={{ background: "var(--background)", border: "1px solid var(--border)", maxHeight: "400px", overflowY: "auto" }}>
            {renderTree(treeNodes)}
          </div>
        </div>
      )}

      {configured && (!tree || tree.length === 0) && (
        <div className="card">
          <div className="text-center py-8">
            <p className="text-sm" style={{ color: "var(--foreground-dim)" }}>
              {tree === null ? "Unable to fetch repo contents. Check your token permissions." : "Repo is empty. Push artifacts to populate it."}
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
